name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:    
      - uses: actions/checkout@v2
      - name: stash the changes
        working-directory: /var/www/sayches1
        run: sudo GIT_SSH_COMMAND="ssh -i ~/root/.ssh/runner" git stash
      - name: pull grom github
        working-directory: /var/www/sayches1
        run: sudo GIT_SSH_COMMAND="ssh -i ~/root/.ssh/runner" git pull
      - name: start docker-compose file
        working-directory: /var/www/sayches1
        run: docker-compose -f local.yml run django python manage.py makemigrations
      - name: 2nd step
        working-directory: /var/www/sayches1
        run: docker-compose -f local.yml run django python manage.py migrate
      - name: 3rd step
        working-directory: /var/www/sayches1
        run: sudo docker-compose -f local.yml run django python manage.py collectstatic
      - name: 3rd step
        working-directory: /var/www/sayches1
        run: make up
